ktor:
  deployment:
    port: ${PORT}

  application:
    modules:
      - com.cnvx.ApplicationKt.module

  security:
    jwt:
      issuer: "upet-backend"
      audience: "upet-app"
      realm: "upet"
      secret: ${JWT_SECRET}

  database:
    url: ${DATABASE_URL}